coverage_service: coveralls
xcodeproj: Cleanse.xcodeproj
workspace: Cleanse.xcworkspace
scheme: Cleanse
output_directory: coverage
ignore:
  - Cleanse/PropertyInjectionArities.swift
  - Cleanse/BinderArities.swift
