# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

update_fastlane

# Lint the project
lane :lint do
    swiftlint(
        ignore_exit_status: false,
        strict: false,
        reporter: 'xcode',
        quiet: true
    )
end

lane :test do
    scan
end

lane :documentation do
    jazzy
end
