# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

# Lint the project
lane :lint do
    swiftlint(
        ignore_exit_status: false,
        strict: false,
        reporter: 'xcode',
        quiet: true
    )
end
